---
driver:
  name: docker
  binary: docker
  use_sudo: false

provisioner:
  name: chef_zero
  require_chef_omnibus: latest

platforms:
  - name: centos-6.6

suites:
  - name: default
    run_list:
      - recipe[ratpoison::default]
    attributes:
